apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: observability
servers: 1
agents: 2
network: observability-net
ports:
  - port: 8080:80    # Ingress HTTP
  - port: 8443:443   # Ingress HTTPS
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:0
      - arg: "--flannel-backend=none"   # Disable default flannel
        nodeFilters:
          - server:0
      - arg: "--disable-network-policy" # Disable k3s default NP handling
        nodeFilters:
          - server:0
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
volumes:
  - volume: /tmp/k3d-storage:/var/lib/rancher/k3s/storage
registries:
  create: true
  config: |
    mirrors:
      "localhost:5000":
        endpoint:
          - http://registry.localhost:5000
